// Wire-format characterization tests (ADR-0056) — written BEFORE the
// signed-token-codec extraction refactor, against the pre-refactor
// access-token.ts / magic-link.ts implementations. These pin the *exact*
// on-wire bytes: `base64url(JSON.stringify(claims))` + "." +
// `HMAC-SHA256(payload, secret)` (base64url digest), with claims key order
// `slug, exp, mode?, email?, owner?` for access tokens and a bare
// base64url(nonceId) payload for magic-link tokens.
//
// HARD CONSTRAINT: tokens/cookies minted by the currently-deployed code must
// still verify after the signed-token codec extraction, and vice versa. These
// golden vectors were generated by running the pre-refactor sign() logic
// standalone (see the extraction PR description) and must NOT change after
// the refactor — if they do, the refactor broke wire compatibility.
import { describe, expect, it } from "vitest";
import { mintAccessToken, readAccessToken } from "./access-token";
import { mintMagicLinkToken, verifyMagicLinkToken } from "./magic-link";

const SECRET = "test-secret-key-of-some-length";
const SLUG = "abcdefghij";
const NOW = 1_700_000_000; // fixed epoch seconds

describe("signed-token wire format (characterization, ADR-0056)", () => {
  describe("access token", () => {
    it("pins the exact bytes of a plain slug+exp token", () => {
      const t = mintAccessToken(SLUG, 900, SECRET, NOW);
      expect(t).toBe(
        "eyJzbHVnIjoiYWJjZGVmZ2hpaiIsImV4cCI6MTcwMDAwMDkwMH0" +
          ".fgzaGLDSfSAjKwHhtIChZIAX0hBSiRA2vPDaoh0SyE4",
      );
      expect(readAccessToken(t, SLUG, SECRET, NOW + 60)).toEqual({
        slug: SLUG,
        exp: NOW + 900,
      });
    });

    it("pins the exact bytes of a mode-bound (password) token", () => {
      const t = mintAccessToken(SLUG, 900, SECRET, NOW, { mode: "password" });
      expect(t).toBe(
        "eyJzbHVnIjoiYWJjZGVmZ2hpaiIsImV4cCI6MTcwMDAwMDkwMCwibW9kZSI6InBhc3N3b3JkIn0" +
          ".Dr2qD8pf_bo_AcA8gZTGRMlugnR5fz4h2ddIqCeCWgI",
      );
      expect(readAccessToken(t, SLUG, SECRET, NOW + 60)).toEqual({
        slug: SLUG,
        exp: NOW + 900,
        mode: "password",
      });
    });

    it("pins the exact bytes of an allowlist token carrying the redeemed email", () => {
      const t = mintAccessToken(SLUG, 604_800, SECRET, NOW, {
        mode: "allowlist",
        email: "a@b.com",
      });
      expect(t).toBe(
        "eyJzbHVnIjoiYWJjZGVmZ2hpaiIsImV4cCI6MTcwMDYwNDgwMCwibW9kZSI6ImFsbG93bGlzdCIsImVtYWlsIjoiYUBiLmNvbSJ9" +
          ".lGjs3MJof-NRKGzFU-qcPSNOSBgPysa8_hAq8pnI_88",
      );
      expect(readAccessToken(t, SLUG, SECRET, NOW + 60)).toEqual({
        slug: SLUG,
        exp: NOW + 604_800,
        mode: "allowlist",
        email: "a@b.com",
      });
    });

    it("pins the exact bytes of an owner-claim token", () => {
      const t = mintAccessToken(SLUG, 86_400, SECRET, NOW, { owner: true });
      expect(t).toBe(
        "eyJzbHVnIjoiYWJjZGVmZ2hpaiIsImV4cCI6MTcwMDA4NjQwMCwib3duZXIiOnRydWV9" +
          ".bbJuilpZlHT6ioG9Vyunhh01f-w8yfg9dFV2szWIuXk",
      );
      expect(readAccessToken(t, SLUG, SECRET, NOW + 60)).toEqual({
        slug: SLUG,
        exp: NOW + 86_400,
        owner: true,
      });
    });

    it("pins the exact bytes + claims key order when mode+email+owner are all set", () => {
      const t = mintAccessToken(SLUG, 900, SECRET, NOW, {
        mode: "allowlist",
        email: "user@example.com",
        owner: true,
      });
      expect(t).toBe(
        "eyJzbHVnIjoiYWJjZGVmZ2hpaiIsImV4cCI6MTcwMDAwMDkwMCwibW9kZSI6ImFsbG93bGlzdCIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsIm93bmVyIjp0cnVlfQ" +
          ".rHf0xSbqDzi92YgAIvFVtFzUSJUblJWwRC77lj7xJBY",
      );
    });
  });

  describe("magic-link token", () => {
    it("pins the exact bytes of a nonce-carrying token", () => {
      const MAGIC_SECRET = "magic-link-hmac-secret";
      const NONCE = "9f1c8a3e-1234-4abc-9def-0123456789ab";
      const t = mintMagicLinkToken(NONCE, MAGIC_SECRET);
      expect(t).toBe(
        "OWYxYzhhM2UtMTIzNC00YWJjLTlkZWYtMDEyMzQ1Njc4OWFi" +
          ".9s97pyyVh1zkJsVH21Kp1T3L2hqHw_26CHhJhSI7Pbw",
      );
      expect(verifyMagicLinkToken(t, MAGIC_SECRET)).toBe(NONCE);
    });
  });

  describe("cross-version compatibility (a token minted by one implementation verifies on the other)", () => {
    it("a hand-pinned pre-refactor access token still verifies today", () => {
      const preRefactorToken =
        "eyJzbHVnIjoiYWJjZGVmZ2hpaiIsImV4cCI6MTcwMDAwMDkwMH0" +
        ".fgzaGLDSfSAjKwHhtIChZIAX0hBSiRA2vPDaoh0SyE4";
      expect(readAccessToken(preRefactorToken, SLUG, SECRET, NOW + 60)).toEqual({
        slug: SLUG,
        exp: NOW + 900,
      });
    });

    it("a hand-pinned pre-refactor magic-link token still verifies today", () => {
      const MAGIC_SECRET = "magic-link-hmac-secret";
      const preRefactorToken =
        "OWYxYzhhM2UtMTIzNC00YWJjLTlkZWYtMDEyMzQ1Njc4OWFi" +
        ".9s97pyyVh1zkJsVH21Kp1T3L2hqHw_26CHhJhSI7Pbw";
      expect(verifyMagicLinkToken(preRefactorToken, MAGIC_SECRET)).toBe(
        "9f1c8a3e-1234-4abc-9def-0123456789ab",
      );
    });
  });
});
