// The `/edit` answer for a report whose stored document the editor cannot open.
//
// WHY THIS EXISTS. These three failures (`document-unreadable`,
// `document-unsplittable`, `document-unparsable`) fire AFTER the gate has
// already returned `serve` against a valid `arp_edit` cookie — the visitor's
// capability is proven, and the request is sitting on the view origin's own
// `/edit` route. Until 2026-08-06 the route answered them with a silent `302`
// to the read-only viewer. For a PRIVATE report that viewer redirects to
// `${appOrigin}/unlock/{slug}`, which denied the owner — so the one person
// entitled to the report clicked Edit, was bounced without explanation, and
// clicking again just repeated it.
//
// The fix is not a better redirect target; it is not redirecting. A rendered
// page carries no `Location`, so the path from a document failure to the unlock
// wall does not exist to be guarded — it is structurally absent. And the user
// finally learns WHY, which the 302 never told them.
//
// Kept deliberately small and pure so the copy and the shape are unit-testable
// (`unopenable.test.ts`) without importing the route, which drags in the whole
// editor bundle. Same idiom as `loader-data.ts`'s `buildEditLoaderExtras`.
import type { DocumentDegradeReason } from "./load-document";

/**
 * `409 Conflict`, not `200` and not a `3xx`.
 *
 * - Not a `3xx`: that is the failure mode being removed (see above).
 * - Not `200`: the request was understood and authorized, but it could not be
 *   completed — a 200 would tell every uptime probe and every log query that
 *   editing worked. RFC 9110's `409` is the honest fit: the conflict is with
 *   "the current state of the target resource" (a stored document the editor
 *   cannot open), and it is one "the user might be able to resolve … and
 *   resubmit" — re-upload an editable document and the same URL works.
 * - Contrast the ADR-0038 §2 scanning holding page, which IS a `200`: that
 *   state is transient and expected to clear on its own. This one does not
 *   clear without the user doing something.
 */
export const UNOPENABLE_STATUS = 409;

/**
 * The user-facing sentence per reason — EXHAUSTIVE over `DocumentDegradeReason`
 * by type, so a fourth reason cannot be added without writing its copy.
 *
 * The reason CODE never appears in the copy: it is a log field
 * (`editUnopenableLine`), and the page is for a person who wants to know
 * whether this is their problem or ours, and what to do next. Each sentence
 * therefore says (a) what happened, in plain language, and (b) the one action
 * that would change the outcome.
 */
export const UNOPENABLE_EXPLANATION: Readonly<Record<DocumentDegradeReason, string>> = {
  "document-unreadable":
    "We couldn’t retrieve this report’s stored file. That’s a problem on our side, not with your report — the report itself is intact, and trying again in a few minutes usually clears it.",
  "document-unsplittable":
    "This report was uploaded as an HTML fragment rather than a complete page, so there’s no document body for the editor to open. Re-upload it as a full HTML page and it will open here.",
  "document-unparsable":
    "This report’s HTML is nested far more deeply than the editor can load — usually a sign it was generated by a tool that wraps every element. Re-upload a flatter version and it will open here.",
};

export interface UnopenableDocumentPayload {
  readonly unopenable: {
    /** The machine reason — mirrors the log line, drives nothing user-visible
     *  beyond selecting the copy. Serialized so a support conversation can
     *  quote it without asking for logs. */
    readonly reason: DocumentDegradeReason;
    readonly explanation: string;
    /** ALWAYS a root-relative path on THIS origin — the read-only view of the
     *  very report the user was trying to edit, `/{slug}` or
     *  `/{slug}?access=<verified owner fallback>`. Never absolute and never
     *  protocol-relative, so it cannot become an off-site jump; enforced by
     *  `rootRelativePath` below rather than merely intended, because the value
     *  now arrives from the caller. */
    readonly readOnlyHref: string;
  };
  readonly docTitle: string;
  readonly slug: string;
}

export interface UnopenableDocumentArgs {
  readonly reason: DocumentDegradeReason;
  readonly slug: string;
  readonly docTitle: string;
  /**
   * Where "Open the read-only view" points — the route's own degrade target,
   * `degradeTargetFor(decision, slug).to` (../server/gate.server.ts).
   *
   * WHY IT IS PASSED IN RATHER THAN BUILT HERE (2026-08-06, second pass). This
   * page originally hard-coded `/{slug}`. For a PRIVATE report that link cannot
   * work: the public viewer sees private + no token and redirects to
   * `${appOrigin}/unlock/{slug}`, whose owner-aware page offers
   * `/reports/{slug}/open` → `/edit` → this page again → the same bare link. A
   * user-driven cycle that never reaches the content. So the owner of a
   * private, unopenable report could read a clear explanation of why they
   * couldn't EDIT it and still could not READ it — the 2026-08-06 lockout in
   * its last remaining form.
   *
   * The route already holds the fix: the `oa` fallback (query or `arp_edit_oa`
   * cookie) that the gate has ALREADY verified with `acceptOwnerFallback`
   * (HMAC + this slug + unexpired + `owner === true`), baked into
   * `decision.degradeTo` as `?access=`. Carrying it here mints NOTHING — the
   * view origin stays credential-free (ADR-0056: the app authorizes, the viewer
   * verifies) — and reuses the ONE degrade-target answer rather than growing a
   * second one, which is exactly the duplication `degradeTargetFor` exists to
   * prevent.
   *
   * Omitted / not root-relative → the bare `/{slug}`, which is the CORRECT link
   * for a write-grantee: `ownerOpenLocation` deliberately never mints them an
   * `oa`, and the unlock page they land on recognises write access.
   */
  readonly readOnlyHref?: string;
}

/**
 * Keep the link on this origin. Today's only caller passes `degradeTargetFor`'s
 * output — built from a validated `Slug` and a percent-encoded, verified token
 * — but the argument's type is `string`, and this anchor is rendered into a
 * page, so the invariant the payload documents is enforced here rather than
 * assumed of every future caller. Anything that isn't an unambiguous
 * root-relative path (absolute, protocol-relative, `/\`-relative — which some
 * browsers normalise to `//` — or a `javascript:`/other scheme) collapses to
 * this report's own path.
 */
function rootRelativePath(href: string | undefined, slug: string): string {
  return href?.startsWith("/") && !href.startsWith("//") && !href.startsWith("/\\")
    ? href
    : `/${slug}`;
}

/** Build the loader payload for the unopenable-document page. Carries no EDIT
 *  capability: the edit token is what the EDITOR render hands the client, and
 *  this is the branch where the editor did not render. The read-only owner
 *  fallback inside `readOnlyHref` is the one token it may carry, and only
 *  because the visitor already presented it on this very request. */
export function unopenableDocument(args: UnopenableDocumentArgs): UnopenableDocumentPayload {
  return {
    unopenable: {
      reason: args.reason,
      explanation: UNOPENABLE_EXPLANATION[args.reason],
      readOnlyHref: rootRelativePath(args.readOnlyHref, args.slug),
    },
    docTitle: args.docTitle,
    slug: args.slug,
  };
}
