// The `/edit` answer for a report whose stored document the editor cannot open.
//
// WHY THIS EXISTS. These three failures (`document-unreadable`,
// `document-unsplittable`, `document-unparsable`) fire AFTER the gate has
// already returned `serve` against a valid `arp_edit` cookie — the visitor's
// capability is proven, and the request is sitting on the view origin's own
// `/edit` route. Until 2026-08-06 the route answered them with a silent `302`
// to the read-only viewer. For a PRIVATE report that viewer redirects to
// `${appOrigin}/unlock/{slug}`, which denied the owner — so the one person
// entitled to the report clicked Edit, was bounced without explanation, and
// clicking again just repeated it.
//
// The fix is not a better redirect target; it is not redirecting. A rendered
// page carries no `Location`, so the path from a document failure to the unlock
// wall does not exist to be guarded — it is structurally absent. And the user
// finally learns WHY, which the 302 never told them.
//
// Kept deliberately small and pure so the copy and the shape are unit-testable
// (`unopenable.test.ts`) without importing the route, which drags in the whole
// editor bundle. Same idiom as `loader-data.ts`'s `buildEditLoaderExtras`.
import type { DocumentDegradeReason } from "./load-document";

/**
 * `409 Conflict`, not `200` and not a `3xx`.
 *
 * - Not a `3xx`: that is the failure mode being removed (see above).
 * - Not `200`: the request was understood and authorized, but it could not be
 *   completed — a 200 would tell every uptime probe and every log query that
 *   editing worked. RFC 9110's `409` is the honest fit: the conflict is with
 *   "the current state of the target resource" (a stored document the editor
 *   cannot open), and it is one "the user might be able to resolve … and
 *   resubmit" — re-upload an editable document and the same URL works.
 * - Contrast the ADR-0038 §2 scanning holding page, which IS a `200`: that
 *   state is transient and expected to clear on its own. This one does not
 *   clear without the user doing something.
 */
export const UNOPENABLE_STATUS = 409;

/**
 * The user-facing sentence per reason — EXHAUSTIVE over `DocumentDegradeReason`
 * by type, so a fourth reason cannot be added without writing its copy.
 *
 * The reason CODE never appears in the copy: it is a log field
 * (`editUnopenableLine`), and the page is for a person who wants to know
 * whether this is their problem or ours, and what to do next. Each sentence
 * therefore says (a) what happened, in plain language, and (b) the one action
 * that would change the outcome.
 */
export const UNOPENABLE_EXPLANATION: Readonly<Record<DocumentDegradeReason, string>> = {
  "document-unreadable":
    "We couldn’t retrieve this report’s stored file. That’s a problem on our side, not with your report — the report itself is intact, and trying again in a few minutes usually clears it.",
  "document-unsplittable":
    "This report was uploaded as an HTML fragment rather than a complete page, so there’s no document body for the editor to open. Re-upload it as a full HTML page and it will open here.",
  "document-unparsable":
    "This report’s HTML is nested far more deeply than the editor can load — usually a sign it was generated by a tool that wraps every element. Re-upload a flatter version and it will open here.",
};

export interface UnopenableDocumentPayload {
  readonly unopenable: {
    /** The machine reason — mirrors the log line, drives nothing user-visible
     *  beyond selecting the copy. Serialized so a support conversation can
     *  quote it without asking for logs. */
    readonly reason: DocumentDegradeReason;
    readonly explanation: string;
    /** ALWAYS a root-relative path built from this report's own slug — the
     *  read-only view of the very report the user was trying to edit. Never an
     *  absolute or protocol-relative URL, so it cannot become an open
     *  redirect if it is ever used as one. */
    readonly readOnlyHref: string;
  };
  readonly docTitle: string;
  readonly slug: string;
}

export interface UnopenableDocumentArgs {
  readonly reason: DocumentDegradeReason;
  readonly slug: string;
  readonly docTitle: string;
}

/** Build the loader payload for the unopenable-document page. Carries NO
 *  capability: the edit token is what the EDITOR render hands the client, and
 *  this is the branch where the editor did not render. */
export function unopenableDocument(args: UnopenableDocumentArgs): UnopenableDocumentPayload {
  return {
    unopenable: {
      reason: args.reason,
      explanation: UNOPENABLE_EXPLANATION[args.reason],
      readOnlyHref: `/${args.slug}`,
    },
    docTitle: args.docTitle,
    slug: args.slug,
  };
}
